In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/MRI image source.txt
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (243).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1062).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (205).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (95).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (14).jpeg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (123).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (281).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (498).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (453).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (494).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (682).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (589).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (237).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (202).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (10).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (447).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (179).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (715).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (352).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (576).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (358).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (508).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (57).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1079).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (734).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1025).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (336).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1054).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (432).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (10).jpeg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (553).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (491).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (130).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (292).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (165).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (77).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (991).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (28).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (308).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (448).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (193).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (472).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (147).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (414).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (530).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (416).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (485).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (275).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (166).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (398).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (208).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (510).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (584).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (543).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (575).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (471).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (116).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (199).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (520).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (459).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (244).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (133).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (219).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (408).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (187).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (481).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (267).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (467).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1091).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (299).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (227).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (951).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (709).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (120).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (583).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (489).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (605).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (366).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (742).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (199).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (211).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (913).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (312).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (263).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1075).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (52).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (761).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (880).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (546).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (382).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (394).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (268).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (102).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (187).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (110).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (569).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (866).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (861).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (628).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (284).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (134).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (345).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (443).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (416).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (333).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (265).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (140).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (355).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (28).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (283).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (302).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (620).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (8).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (192).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (242).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (559).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (602).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (169).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (247).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (147).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (512).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (646).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (13).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1107).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (869).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (157).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (597).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (63).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (160).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (870).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (400).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (525).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (954).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (284).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (148).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1007).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (1077).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (512).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (320).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (604).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (353).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/glioma (664).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (230).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (569).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (687).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (541).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/meningioma (376).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/tumor (86).jpg
/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images/Tumor/pituitary (180).jpg

In [2]:
ct_scan_base_path="/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor CT scan Images"
mri_scan_base_path="/kaggle/input/datasets/murtozalikhon/brain-tumor-multimodal-image-ct-and-mri/Dataset/Brain Tumor MRI images"
categories=["Healthy","Tumor"]

In [3]:
import os
import pandas as pd

image_paths=[]
labels=[]

for category in categories:
    category_path=os.path.join(mri_scan_base_path,category)
    images= os.listdir(category_path)[:2000]

    for image_name in images:
        image_path = os.path.join(category_path, image_name)
        image_paths.append(image_path)
        labels.append(category)

df = pd.DataFrame({
    "image_path": image_paths,
    "label": labels
})

In [4]:
df.head()

                                          image_path    label
0  /kaggle/input/datasets/murtozalikhon/brain-tum...  Healthy
1  /kaggle/input/datasets/murtozalikhon/brain-tum...  Healthy
2  /kaggle/input/datasets/murtozalikhon/brain-tum...  Healthy
3  /kaggle/input/datasets/murtozalikhon/brain-tum...  Healthy
4  /kaggle/input/datasets/murtozalikhon/brain-tum...  Healthy

In [5]:
df.tail()

                                             image_path  label
3995  /kaggle/input/datasets/murtozalikhon/brain-tum...  Tumor
3996  /kaggle/input/datasets/murtozalikhon/brain-tum...  Tumor
3997  /kaggle/input/datasets/murtozalikhon/brain-tum...  Tumor
3998  /kaggle/input/datasets/murtozalikhon/brain-tum...  Tumor
3999  /kaggle/input/datasets/murtozalikhon/brain-tum...  Tumor

In [6]:
df.columns

Index(['image_path', 'label'], dtype='object')

In [7]:
df.shape

(4000, 2)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull().sum()

image_path    0
label         0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   image_path  4000 non-null   object
 1   label       4000 non-null   object
dtypes: object(2)
memory usage: 62.6+ KB